import React, { Component } from 'react';

class Body extends Component {
  render() {
    return (
      <div className='body'>
      <p><b>Aim:</b> To generate a single-line melody that is musical in nature.</p>
      <p><b>Intended Audience:</b> Students preparing for practical music examinations (offered by AMEB, ABRSM) that require sight-reading. The sight-reading component of practical music examinations involve the student being given a melody that they have not previously seen before, and after a short period (e.g. a minute) of study, the student is expected to play the given melody as fluently as possible.<br />
      This app also has the potential to give students feedback on their sight-reading, by comparing student input (i.e. the student plays the melody into a microphone) to the synthesised version generated by the app.<br /> <br />

      Composers may also be interested in the mathematical algorithms and ideas utilised within, either as part of computer-aided composition or as to integrate similar ideas into their works.</p>
      <p>Instructions: <br/>
        <ul>
          <li>Click on the 'Randomise!' button to generate a melody.</li>
          <li>Click 'Play!' to hear the generated melody played using a synthesiser.</li>
        </ul>
      </p>
      </div>
    )
  }
}

export default Body;
